base_model: /opt/ml/input/data/model
base_model_config: /opt/ml/input/data/model

model_type: LlamaForCausalLM
tokenizer_type: LlamaTokenizer
load_in_8bit: false
load_in_4bit: true
strict: false


datasets:
  - path: /opt/ml/input/data/train/Open-Platypus.json
    ds_type: json 
    type: alpaca

dataset_prepared_path: /tmp/last_run_prepared
val_set_size: 0.01
output_dir: /opt/ml/model

dataset_prepared_path: last_run_prepared
val_set_size: 0.02
adapter: qlora
lora_model_dir:

sequence_len: 4096
sample_packing: true
pad_to_sequence_len: true

lora_r: 32
lora_alpha: 16
lora_dropout: 0.05
lora_target_modules:
lora_target_linear: true
lora_fan_in_fan_out:

output_dir: /opt/ml/model
checkpoint_dir: /opt/ml/checkpoints

gradient_accumulation_steps: 2
micro_batch_size: 2
num_epochs: 2
optimizer: paged_adamw_32bit
torchdistx_path:
lr_scheduler: cosine
learning_rate: 0.0002
train_on_inputs: false
group_by_length: false
bf16: true
fp16: false
tf32: false
gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true
gptq_groupsize:
gptq_model_v1:
warmup_steps: 10
eval_steps: 50
save_strategy: "no"
save_total_limit: 1
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
  bos_token: "<s>"
  eos_token: "</s>"
  unk_token: "<unk>"
report_to: "tensorboard"
logging_dir: "/opt/ml/output/tensorboard"
